name: 'Find Sha1-Hulud Activity'
description: 'Custom action to look for potential Sha1-Hulud activity related to your GitHub Enterprise'
author: 'Paul Wideman'

branding:
  icon: 'search'
  color: 'orange'

runs:
  using: 'node20'
  main: 'dist/index.js'
